---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/favaretto46/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r css/ $DEPLOYPATH
    - /bin/cp -r fonts/ $DEPLOYPATH
    - /bin/cp -r img/ $DEPLOYPATH
    - /bin/cp -r js/ $DEPLOYPATH
