---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/favaretto46/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp estilo.css $DEPLOYPATH
    - /bin/cp file-code-solid.svg $DEPLOYPATH
